# CMake generated Testfile for 
# Source directory: /home/elizabethli/cmsc220/chiventure
# Build directory: /home/elizabethli/cmsc220/chiventure/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("src/action_management")
subdirs("src/battle")
subdirs("src/cli")
subdirs("src/common")
subdirs("src/custom-actions")
subdirs("src/game-state")
subdirs("src/libobj")
subdirs("src/quests")
subdirs("src/sound")
subdirs("src/npc")
subdirs("src/openworld")
subdirs("src/playerclass")
subdirs("src/skilltrees")
subdirs("src/ui")
subdirs("src/wdl")
subdirs("src/custom-scripts")
subdirs("tests/action_management")
subdirs("tests/battle")
subdirs("tests/cli")
subdirs("tests/custom-actions")
subdirs("tests/game-state")
subdirs("tests/libobj")
subdirs("tests/quests")
subdirs("tests/npc")
subdirs("tests/openworld")
subdirs("tests/playerclass")
subdirs("tests/skilltrees")
subdirs("tests/ui")
subdirs("tests/wdl")
subdirs("tests/custom-scripts")
