/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample.proto */

#ifndef PROTOBUF_C_sample_2eproto__INCLUDED
#define PROTOBUF_C_sample_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Game Game;
typedef struct _Game__Room Game__Room;
typedef struct _Game__Player Game__Player;


/* --- enums --- */


/* --- messages --- */

struct  _Game__Room
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean exit;
  protobuf_c_boolean has_connected_rooms;
  int32_t connected_rooms;
};
#define GAME__ROOM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__room__descriptor) \
    , NULL, 0, 0,0 }


struct  _Game__Player
{
  ProtobufCMessage base;
  Game__Room *location;
};
#define GAME__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__player__descriptor) \
    , NULL }


struct  _Game
{
  ProtobufCMessage base;
  size_t n_rooms;
  Game__Room **rooms;
  Game__Player *player;
};
#define GAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__descriptor) \
    , 0,NULL, NULL }


/* Game__Room methods */
void   game__room__init
                     (Game__Room         *message);
/* Game__Player methods */
void   game__player__init
                     (Game__Player         *message);
/* Game methods */
void   game__init
                     (Game         *message);
size_t game__get_packed_size
                     (const Game   *message);
size_t game__pack
                     (const Game   *message,
                      uint8_t             *out);
size_t game__pack_to_buffer
                     (const Game   *message,
                      ProtobufCBuffer     *buffer);
Game *
       game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__free_unpacked
                     (Game *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__Room_Closure)
                 (const Game__Room *message,
                  void *closure_data);
typedef void (*Game__Player_Closure)
                 (const Game__Player *message,
                  void *closure_data);
typedef void (*Game_Closure)
                 (const Game *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor game__descriptor;
extern const ProtobufCMessageDescriptor game__room__descriptor;
extern const ProtobufCMessageDescriptor game__player__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sample_2eproto__INCLUDED */
