/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sample.pb-c.h"
void   player__init
                     (Player         *message)
{
  static Player init_value = PLAYER__INIT;
  *message = init_value;
}
size_t player__get_packed_size
                     (const Player *message)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player__pack
                     (const Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player__pack_to_buffer
                     (const Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Player *)
     protobuf_c_message_unpack (&player__descriptor,
                                allocator, len, data);
}
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   room__init
                     (Room         *message)
{
  static Room init_value = ROOM__INIT;
  *message = init_value;
}
size_t room__get_packed_size
                     (const Room *message)
{
  assert(message->base.descriptor == &room__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t room__pack
                     (const Room *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &room__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t room__pack_to_buffer
                     (const Room *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &room__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Room *
       room__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Room *)
     protobuf_c_message_unpack (&room__descriptor,
                                allocator, len, data);
}
void   room__free_unpacked
                     (Room *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &room__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__init
                     (Game         *message)
{
  static Game init_value = GAME__INIT;
  *message = init_value;
}
size_t game__get_packed_size
                     (const Game *message)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pack
                     (const Game *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pack_to_buffer
                     (const Game *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game *
       game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game *)
     protobuf_c_message_unpack (&game__descriptor,
                                allocator, len, data);
}
void   game__free_unpacked
                     (Game *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &game__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor player__field_descriptors[1] =
{
  {
    "p_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Player, p_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player__field_indices_by_name[] = {
  0,   /* field[0] = p_name */
};
static const ProtobufCIntRange player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Player",
  "Player",
  "Player",
  "",
  sizeof(Player),
  1,
  player__field_descriptors,
  player__field_indices_by_name,
  1,  player__number_ranges,
  (ProtobufCMessageInit) player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor room__field_descriptors[1] =
{
  {
    "r_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Room, r_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned room__field_indices_by_name[] = {
  0,   /* field[0] = r_name */
};
static const ProtobufCIntRange room__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor room__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Room",
  "Room",
  "Room",
  "",
  sizeof(Room),
  1,
  room__field_descriptors,
  room__field_indices_by_name,
  1,  room__number_ranges,
  (ProtobufCMessageInit) room__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__field_descriptors[3] =
{
  {
    "player_info",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Game, player_info),
    &player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Game, location),
    &room__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discovered",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Game, has_discovered),
    offsetof(Game, discovered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__field_indices_by_name[] = {
  2,   /* field[2] = discovered */
  1,   /* field[1] = location */
  0,   /* field[0] = player_info */
};
static const ProtobufCIntRange game__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Game",
  "Game",
  "Game",
  "",
  sizeof(Game),
  3,
  game__field_descriptors,
  game__field_indices_by_name,
  1,  game__number_ranges,
  (ProtobufCMessageInit) game__init,
  NULL,NULL,NULL    /* reserved[123] */
};
