/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sample.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sample.pb-c.h"
void   game__room__init
                     (Game__Room         *message)
{
  static Game__Room init_value = GAME__ROOM__INIT;
  *message = init_value;
}
void   game__player__init
                     (Game__Player         *message)
{
  static Game__Player init_value = GAME__PLAYER__INIT;
  *message = init_value;
}
void   game__init
                     (Game         *message)
{
  static Game init_value = GAME__INIT;
  *message = init_value;
}
size_t game__get_packed_size
                     (const Game *message)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pack
                     (const Game *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pack_to_buffer
                     (const Game *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game *
       game__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game *)
     protobuf_c_message_unpack (&game__descriptor,
                                allocator, len, data);
}
void   game__free_unpacked
                     (Game *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &game__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor game__room__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Game__Room, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Game__Room, exit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_rooms",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Game__Room, has_connected_rooms),
    offsetof(Game__Room, connected_rooms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__room__field_indices_by_name[] = {
  2,   /* field[2] = connected_rooms */
  1,   /* field[1] = exit */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange game__room__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__room__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Game.Room",
  "Room",
  "Game__Room",
  "",
  sizeof(Game__Room),
  3,
  game__room__field_descriptors,
  game__room__field_indices_by_name,
  1,  game__room__number_ranges,
  (ProtobufCMessageInit) game__room__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__player__field_descriptors[1] =
{
  {
    "location",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Game__Player, location),
    &game__room__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__player__field_indices_by_name[] = {
  0,   /* field[0] = location */
};
static const ProtobufCIntRange game__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor game__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Game.Player",
  "Player",
  "Game__Player",
  "",
  sizeof(Game__Player),
  1,
  game__player__field_descriptors,
  game__player__field_indices_by_name,
  1,  game__player__number_ranges,
  (ProtobufCMessageInit) game__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__field_descriptors[2] =
{
  {
    "rooms",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Game, n_rooms),
    offsetof(Game, rooms),
    &game__room__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Game, player),
    &game__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__field_indices_by_name[] = {
  1,   /* field[1] = player */
  0,   /* field[0] = rooms */
};
static const ProtobufCIntRange game__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Game",
  "Game",
  "Game",
  "",
  sizeof(Game),
  2,
  game__field_descriptors,
  game__field_indices_by_name,
  1,  game__number_ranges,
  (ProtobufCMessageInit) game__init,
  NULL,NULL,NULL    /* reserved[123] */
};
