# Makefile for using library and connecting our files
# compiler
CC = gcc
# compiler flags
CFLAGS =
# remove command
RM = rm -f
# library flags
LDFLAGS = -L../libobj/ -Wl,-rpath=../libobj/
# library name
LIB = -l
