// ?start: assignment
?start: (assignment | reference | other)* -> start

_TRIPLE_QUOTES: "\"\"\""
assignment.10: "$" CNAME "=" (_triple_quotes | ESCAPED_STRING)

_triple_quotes.10: _TRIPLE_QUOTES assignment_inner _TRIPLE_QUOTES

// matches up to triple quotes
assignment_inner: /[^\$]+?(?=""")/

reference.5: "$" CNAME

// matches anything other than $ because $ denotes variables
other: /[^\$]+/

%import common.CNAME
%import .util.ESCAPED_STRING

%import common.WS_INLINE
%ignore WS_INLINE