//#include "custom-scripts/custom_types.h"
#include "custom-scripts/custom_types.h"

// see custom_type.h
obj_t obj_t_new()
{
    obj_t ot;
    ot.type = TYPE_NONE;
    return ot;
}

// see custom_type.h
obj_t obj_t_bool(bool b)
{
    obj_t ot = obj_t_new();
    ot.type = TYPE_BOOL;
    ot.data = b;
    return ot;
}

// see custom_type.h
obj_t obj_t_char(char c)
{
    obj_t ot = obj_t_new();
    ot.type = TYPE_CHAR;
    ot.data = c;
    return ot;
}

// see custom_type.h
obj_t obj_t_int(int i)
{
    obj_t ot = obj_t_new();
    ot.type = TYPE_INT;
    ot.data = i;
    return ot;
}

// see custom_type.h
obj_t obj_t_str(char *s)
{
    obj_t ot = obj_t_new();
    ot.type = TYPE_STR;
    ot.data = s;
    return ot;
}

// see custom_type.h
obj_t obj_t_lua(char *lua)
{
    obj_t ot = obj_t_new();
    ot.type = TYPE_LUA;
    ot.data = lua;
    return ot;
}

// see custom_types.h
bool bool_t_get(obj_t ot) {
    assert(ot.type == TYPE_BOOL);
    return ot.data.b;
}

// see custom_types.h
char char_t_get(obj_t ot) {
    assert(ot.type == TYPE_CHAR);
    return ot.data.c;
}

// see custom_types.h
int int_t_get(obj_t ot) {
    assert(ot.type == TYPE_INT);
    return ot.data.i;
}

// see custom_types.h
char* str_t_get(obj_t ot) {
    assert(ot.type == TYPE_STR);
    return ot.data.s;
}

// see custom_types.h
char* lua_t_get(obj_t ot) {
    assert(ot.type == TYPE_LUA);
    // but our original intention was not to return the Lua directory
    // but to return the output generated by the Lua directory
    //return ot.data.lua;
}


// see custom_types.h
bool string_is_lua(char* s) {
    if (!(s)) { // string is NULL
        return false;
    }
    if (s[0] == 'L' && s[1] == 'U' && s[2] == 'A' && s[3] == ' ') {
        return true;
    } else {
        return false;
    }
}

// see custom_types.h
char* extract_lua(char* s) {
    return s + 4; // remove the first 4 characters of the string
}